[package]
name = "rustbustools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib ="0.39"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"
# flate2 = "1.0"
# regex = "1"
# lazy_static = "1"
# serde_json = "1.0"
# rusqlite = "0.27"
# fastq = "0.6"
#counter = "0.5"
#bktree = "1"
#polars = {version = "0.21", features =["parquet", "lazy"]}
#streaming_algorithms = "*"
#indicatif = "0.16"
clap = { version = "3.1.18", features = ["derive"] }